### ISSUE TITLE
Procedure to upload this code to Arduino

### ISSUE THREAD

**Issue by ramabaruva** [KIHestad/ArduMcController#1]
Hello ,
I was very impressed by the initiative and work done, 
I am trying to implement the same on my bike .
But got stuck on step one ,as I am not a programmer.
can you please share the details on procedure how to use the code and deploy it on the Arduino.
a video will also help for the same.
Also please uploaded the circuit diagram of the finished wiring setup.

Regards
Rama

**Comment by KIHestad** [comment]
Hey, sorry for not replying. I had not noticed this request. The project has been paused for a while, but I am starting up again now.

I hope to share some news very soon, will be posted a video on YouTube later this summer.
